### ISSUE TITLE
Wi-fi

### ISSUE THREAD

**Issue by RafaelYassue** [farmbeatslabs/FBLKv2#2]
I have a Microsoft FarmBeats Student Kit and I am having two problems:
1. I have a pre-installed SD Card with FarmBeatsLabs installed, Although I was not able to config my Wi-Fi connection. Is possible to connect to a new Wi-fi?
2. I tried to re-install  FarmBeatsLabs in another SD Card. I have installed  Windows 10 IoT Core and FarmBeats Sensor Application Software according to the tutorial. Although, when I re-boot my device, it will not open the FarmBeats app. Is there anything I can do?

**Comment by JT73** [comment]
to configure a new wifi you book the device and log in remotely to the Windows Device Portal. 
https://docs.microsoft.com/en-us/windows/iot-core/connect-your-device/setupwifi
